### PR TITLE
Rian CSSday2 and JS exercises

### PR DESCRIPTION
**Pull request by rbEY22**

### CODE REVIEW

**Comment by rbEY22** [comment]
Added screenshots of completed CSS exercises. Also, completed and added JS exercises with screenshot.

**Comment by rbEY22** [comment]
specificity_2022_09_14_2_01
css_holygrail_exercise
CSS_udemy
css2_exercise1
css2_udemy
flukeout_2022_09_14_1_48

**Comment by rbEY22** [comment]
JS_exercise1
JS_exercise2
JS_udemy
JS_w3schools

**Comment by rbEY22** [comment]
GreenBlue

**Comment by rbEY22** [comment]
HelloWorld
ImageAlert
Semantics
GreenBlue

**Comment by rbEY22** [comment]
Java_remove_idx_userinput
Java_righmost_userinput
Java_student_exercise
Java_sum_strings_userinput
java_udemy1
java_udemy2
java_udemy3
java_udemy4
Java_book_exercise
Java_exercises1
Java_exercises2
Java_pattern_userinput
Java_rect_exercise

**Review by madhanramu — APPROVED** [review]

**Pull request merged**
